package model;

import org.hibernate.SessionFactory;

/*
 * Class to reduce amount of SessionFactories generated by
 * the DAO classes.
 */

public class DAOManager {
	//static Istuntotehdas istuntotehdas = null;
	AsiakasAccessObject asiakasDAO = null;
	static HenkilökuntaAccessObject henkilökuntaDAO = null;
	ReseptiAccessObject reseptiDAO = null;
	SairausAccessObject sairausDAO = null;
	VeriarvoAccessObject veriarvoDAO = null;
	SessionFactory s;
	


	public DAOManager() {
		s =Istuntotehdas.getSessionFactory();
	}

	public AsiakasAccessObject getAsiakasDAO() {
		if (this.asiakasDAO == null) {
			this.asiakasDAO = new AsiakasAccessObject(s);
		}
		return this.asiakasDAO;
	}

	public HenkilökuntaAccessObject getHenkilökuntaDAO() {
		

		if (henkilökuntaDAO == null) {
			henkilökuntaDAO = new HenkilökuntaAccessObject(s);
		}
		return henkilökuntaDAO;
	}

	public ReseptiAccessObject getReseptiDAO() {
		if (this.reseptiDAO == null) {
			this.reseptiDAO = new ReseptiAccessObject(s);
		}
		return this.reseptiDAO;
	}

	public SairausAccessObject getSairausDAO() {
		if (this.sairausDAO == null) {
			this.sairausDAO = new SairausAccessObject(s);
		}
		return this.sairausDAO;
	}

	public VeriarvoAccessObject getVeriarvoDAO() {
		if (this.veriarvoDAO == null) {
			this.veriarvoDAO = new VeriarvoAccessObject(s);
		}
		return this.veriarvoDAO;
	}
}
